# Simple example of deploying a privileged pod, with a host volume mount
apiVersion: v1
kind: Pod
metadata:
  name: snyky-priv
  namespace: kube-system
spec:
  containers:
  - name: snyky-priv
    image: ericsmalling/snyky:23.0
    volumeMounts:
      - mountPath: /chroot
        name: host
    securityContext:
      runAsUser: 999
      privileged: true
  volumes:
  - name: host
    hostPath:
      path: /
      type: Directory
